site_name: 笔记
site_description: 笔记
site_author: 流浪地球

repo_name: 'caimengzhi/books'
repo_url: 'https://github.com/caimengzhi/books'
theme:
  name: material
  #name: readthedocs
  highlightjs: true
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  language: 'zh'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

extra:
  social:
    - type: github
      link: https://github.com/caimengzhi
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  #- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  #- 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'
  #- 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
  #- 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'
  #- 'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'
  #- 'js/umlconvert.js'
  - js/webfont.js
  - js/snap.svg-min.js
  - js/underscore-min.js
  - js/sequence-diagram-min.js   
  - js/uml-converter.js
  - js/sequence-loader.js

nav:
    - Python:
        - 工具:
            - 虚拟环境:
                - 1. virtualenv: python/tools/virtualenv.index.md
                - 2. virtualenvwrapper: python/tools/virtualenvwrapper.index.md
        - 库学习:
            - 1. SQLAlchemy库:  
                - 1. 创建表: python/lib/SQLAlchemy/1.创建表.md
                - 2. 基本操作: python/lib/SQLAlchemy/2.基本操作.md
                - 3. 回滚: python/lib/SQLAlchemy/3.回滚.md
                - 4. 统计分组: python/lib/SQLAlchemy/4.统计分组.md
                - 5. 外键: python/lib/SQLAlchemy/5.外键.md
                - 6. 关系定义: python/lib/SQLAlchemy/6.关系定义.md
            - 2. YAML库:
                - 1. yaml语法: python/lib/yaml/1.yaml语法.md
                - 2. yaml使用: python/lib/yaml/2.yaml使用.md
            - 3. sh库:
                - 1. sh使用: python/lib/sh/1.sh.md
            - 4. excel库:
                - 1. xlrd_xlwt: python/lib/execel/1.xlrd_xlwt.md
                - 2. openpyxl: python/lib/execel/2.openpyxl.md
            - 5. 加解密库:
                - 1. base4: python/lib/encryption_decryption/base64/1.base64使用.md
                - 2. 加解密execl表: python/lib/encryption_decryption/base64/2.案例.md
            - 6. 邮件库:
                - 1. smtp: python/lib/email/smtp/lib_smtp.md
                - 2. yagmail: python/lib/email/smtp/lib_yagmail.md
            - 7. wordcloud库:
                - 1. wordcloud: python/lib/wordcloud/1.wordcloud.md
            - 8. yield库:   python/lib/yield/1.yield.md 
            - 9. Nosql:
                - 1. mongo: python/lib/nosql/mongo/mongo.index.md
                - 2. memcached: python/lib/nosql/memcached/memcached.index.md
                - 3. redis:
                    - 1. redis: python/lib/nosql/redis/redis.index.md
                    - 2. redis pipeline: python/lib/nosql/redis/redis.pipeline.md
                    - 3. redis transaction: python/lib/nosql/redis/redis.transaction.md
                    - 4. redis pub_sub: python/lib/nosql/redis/redis.pub_sub.md
                    - 5. redis sentinel: python/lib/nosql/redis/redis.sentinel.md
            - 10. 数据处理库: 
                - 1. numPy: 
                    - 1. 介绍: python/lib/numPy/1.index.md
                - 2. pandas: 
                    - 1. 介绍: python/lib/pandas/1.index.md   
            - 11. uuid: python/lib/uuid/uuid.index.md
            - 12. LRU: python/lib/LRU/LRU.index.md
            - 13. getpass: python/lib/getpass/getpass.index.md
            - 14. os: python/lib/os/os.index.md
            - 15. sys: python/lib/sys/sys.index.md
            - 16. psutil: python/lib/psutil/psutil.index.md
        - 其他:
            - 1. 列表: python/note/note.extend_append.md
    - Flask:
        - 1. 简介: python/flask/flask.index.md
        - 2. 配置: python/flask/flask.config.md
        - 3. 路由: python/flask/flask.view.md
        - 4. 请求方法: python/flask/flask.methods.md
        - 5. 模板: python/flask/flask.jinja2.md
    - Django:
        - 知识点:
            - 1. 表单空:  python/django/note/django.blank.md
        - 组件:
            - 1. name: python/django/note/django.url_name.md
            - 2. 重名url: python/django/note/django.duplication_url_name.md
            - 3. url 反向解析: python/django/url/django.reverse_url.md
            - 4. 分页器: python/django/url/django.paginator.md
            - 5. 表单: python/django/form/django.form.md
            - 6. 中间件: python/django/middleware/django.middleware.md
    - Hadoop:
        - CDH:
            - 1. CDH 介绍: hadoop/CDH/cdh.index.md
            - 2. CDH 部署: hadoop/CDH/cdh.deploy.md
            - 3. NameNode HA: hadoop/CDH/cdh.namenode_ha.md
        - HDFS:
            - 1. HDFS 介绍: hadoop/CDH/cdh.hdfs_info.md
            - 2. HDFS shell: hadoop/CDH/cdh.hdfs_shell.md
            - 3. secondary_namenode: hadoop/CDH/cdh.secondary_namenode.md
        - Hive:
            - 1. Hive 介绍: hadoop/CDH/cdh.hive.md
    - DStorage:
        - 对比: linux/distributed_storage/distributed_storage.info.md
    - Linux:
        - url: url/url.index.md
        - raid: 
            - 1. raid 介绍: linux/raid/raid.index.md
            - 2. raid 实战: linux/raid/raid.card.md
        - 小工具: 
            - 1. elinks: tools/elinks/elinks.index.md
            - 2. Linux终端录屏和回放: tools/script_scriptreplay/1.index.md
            - 3. xshell:
                - 1. xshell迁移数据: tools/xshell/xshell.index.md
                - 2. xshell无声配置: tools/xshell/xshell.silent.md
            - 4. 下载:
                - 1. axel: linux/tools/axel.index.md

        - 服务:
            - 1. Harbor: linux/server/harbor/harbor.index.md
            - 2. PPPOE: linux/server/pppoe/pppoe.index.md
            - 3. django项目部署: linux/server/deploy_django/deploy_django.index.md
            - 4. sersync: linux/server/sersync/sersync.md
        - 证书:
            - 1. Tomcat: linux/server/certificate/tomcat.index.md
        - shell脚本:
            - 1. 系统巡检: linux/shell/system/linux.system_check.md
            - 2. 网卡信息: linux/shell/system/linux.network.md
            - 3. mysql:
                - 1. 安装: linux/shell/mysql/install/mysql.install.md
    - Nginx:
        - 1. nginx 部署: linux/nginx/nginx.index.md
        - 2. nginx 配置文件: linux/nginx/nginx.conf.md
        - 3. nginx 虚拟主机: linux/nginx/nginx.virtual_hosts.md
        - 4. nginx 日志: linux/nginx/nginx.log.md
        - 5. nginx 防盗链: linux/nginx/nginx.nti_theft_chain.md
        - 6. nginx 常见配置: linux/nginx/nginx.other.md
        - 7. nginx 优化: linux/nginx/nginx.optimization.md
        - 8. nginx hash: linux/nginx/nginx.hash.md
        - 9. nginx location: linux/nginx/nginx.location.md
        - 10. nginx rewrite: linux/nginx/nginx.rewrite.md
        - 11. nginx 负载均衡: linux/nginx/nginx.slb.md
        - 12. nginx http2: linux/nginx/nginx.http2.md
    - Nosql:
        - 1. MonogoDB:
            - 1. MonogoDB 介绍: linux/nosql/mongo/mongo.index.md
            - 2. MonogoDB 数据库: linux/nosql/mongo/mongo.databases.md
            - 3. MonogoDB 集合: linux/nosql/mongo/mongo.collection.md
            - 4. MonogoDB 文档: linux/nosql/mongo/mongo.doc.md
            - 5. MonogoDB 条件查询: linux/nosql/mongo/mongo.conditional_query.md
            - 6. MonogoDB 模糊查询: linux/nosql/mongo/mongo.fuzzy_enquiry.md
            - 7. MonogoDB $type: linux/nosql/mongo/mongo.type.md
            - 8. MonogoDB LS: linux/nosql/mongo/mongo.limit_skip.md
            - 9. MonogoDB 排序: linux/nosql/mongo/mongo.sort.md
            - 10. MonogoDB 备份与恢复: linux/nosql/mongo/mongo.backup_recovery.md
            - 11. MonogoDB 监控: linux/nosql/mongo/mongo.monitor.md 
            - 12. MonogoDB 副本集: linux/nosql/mongo/mongo.replication.md 
            - 13. MonogoDB 分片集: linux/nosql/mongo/mongo.shard_info.md 
            - 14. MonogoDB 分片集实战: linux/nosql/mongo/mongo.shard_replicat.md
        - 2. redis:
            - 1. redis 介绍: linux/nosql/redis/redis.index.md
            - 2. redis 安装: linux/nosql/redis/redis.install.md
            - 3. redis 认证: linux/nosql/redis/redis.auth.md
            - 4. redis 键值对: linux/nosql/redis/redis.k_v.md
            - 5. redis 发布订阅: linux/nosql/redis/redis.publish.md
            - 6. redis 事务: linux/nosql/redis/redis.arrairs.md
            - 7. redis 持久化存储: linux/nosql/redis/redis.store.md
            - 8. redis 备份与恢复: linux/nosql/redis/redis.save.md
            - 9. redis 集群: linux/nosql/redis/redis.sentinel_cluster.md
            - 10. redis 主从: linux/nosql/redis/redis.master-slave.md
            - 11. redis 哨兵: linux/nosql/redis/redis.sentinel.md
            - 12. redis cluster: linux/nosql/redis/redis.cluster.md  
            - 13. redis 缓存策略: linux/nosql/redis/redis.cache_policy.md
            - 14. redis 击穿: linux/nosql/redis/redis.breakdown.md
            - 15. redis 雪崩: linux/nosql/redis/redis.avalanche.md
        - 3. memcached:
            - 1. memcached: linux/nosql/memcached/memcached.index.md
    - mysql:
        - 1. MySQL 基础:
            - 1. MySQL 介绍: mysql/mysql.index.md
            - 2. MySQL 初识: mysql/mysql.info.md
            - 3. MySQL 链接: mysql/mysql.conn.md
            - 4. MySQL 库: mysql/mysql.database.md
            - 5. MySQL 表: mysql/mysql.table.md
            - 6. SQL SELECT: mysql/mysql.select.md
            - 7. SQL WHERE: mysql/mysql.where.md
            - 8. SQL UPDATE: mysql/mysql.update.md
            - 9. SQL DELETE: mysql/mysql.delete.md
            - 10. SQL LIKE: mysql/mysql.like.md
            - 11. SQL DISTINCT: mysql/mysql.distinct.md
            - 12. SQL LIMIT: mysql/mysql.limit.md
            - 13. SQL AND_OR: mysql/mysql.and_or.md
            - 14. SQL ORDER: mysql/mysql.orderby.md
            - 15. SQL INSERT: mysql/mysql.insert.md
            - 16. SQL DESC: mysql/mysql.desc.md
            - 17. SQL IN: mysql/mysql.in.md
            - 18. SQL BETWEEN: mysql/mysql.between.md
            - 19. SQL ALIAS: mysql/mysql.alias.md
            - 20. SQL GRANT: mysql/mysql.grant.md
            - 21. SQL ALTER: mysql/mysql.alter.md
        - 2. MySQL 进阶:
            - 1. SQL PK: mysql/mysql.pk.md
            - 2. SQL INCREMENT: mysql/mysql.increment.md
            - 3. SQL 事务: mysql/mysql.transaction.md
            - 4. NULL: mysql/mysql.null.md
            - 5. 正则: mysql/mysql.regexp.md
            - 6. 多表查询: mysql/mysql.multi_table_query.md
        - 3. MySQL 容灾:
            - 1. mysqldump 参数: mysql/mysql.mysqldump.md
            - 2. mysqldump 脚本: mysql/mysql.mysqldump_case.md
            - 3. xtrabackup: linux/server/xtrabackup/xtrabackup.index.md
            - 4. binlog 恢复数据: mysql/mysql.restore_data.md
        - 4. MySQL 复制:
            - 1. 主从: mysql/mysql.master-slave.md
            - 2. 主主: mysql/mysql.master-master.md
        - 5. MySQL OTHER:
            - 1. MySQL练习: mysql/mysql.practice1.md
            - 2. 配置文件: mysql/mysql.mysqlcnf.md
            - 3. 自增/偏移量: mysql/mysql.increment_offset.md
            - 4. 表删除: mysql/mysql.delete_truncate_drop.md
            - 5. binlog 介绍: mysql/mysql.binlog.md
            - 6. 完整性约束: mysql/mysql.integrity_constraint.md
            - 7. 表复制: mysql/mysql.copy_table.md
            - 8. 存储引擎: mysql/mysql.storage_engine.md
            - 9. 用户: mysql/mysql.user.md            
            - 10. 事务: mysql/mysql.affairs.md            
    - 前端:
          - Vue: frontend/vue/index.md
          - CSS: frontend/css/css.index.md
    - 服务:
          - 1. git: 
            - 1. git: tools/git/git.index.md
            - 2. git 回滚: tools/git/git.rollback.md
            - 3. git 分支: tools/git/git.branch.md
            - 4. git 标签: tools/git/git.label.md
            - 5. git 分支管理: tools/git/git.standard.md
          - 2. github: tools/github/github.index.md
          - 3. gitlab:
            - 1. gitlab: tools/gitlab/gitlab.index.md
            - 2. 关闭注册: tools/gitlab/gitlab.close_register.md
            - 3. 找回root密码: tools/gitlab/gitlab.set_root_pwd.md
    - 教程:
          - 教程: course/index.md
          
    - 测试:
      - 服务:
          - mkdocs 服务:
              - 一. 介绍: index.md
              - 二. 安装:
                  - 1. 本地环境搭建: install/local.md
                  - 2. 发布至GitHub Pages: install/github-pages.md
                  - 3. 发布至自己的HTTP Server: install/http-server.md
              - 三. 语法:
                  - 1. 语法总览: syntax/main.md
                  - 2. 标题: syntax/headline.md
                  - 3. 段落: syntax/paragraph.md
                  - 4. 引用: syntax/quote.md
                  - 5. 表格: syntax/table.md
                  - 6. 代码:
                      - 6.1. 行内: syntax/code_inline.md
                      - 6.2. 区块: syntax/code_block.md
                      - 6.3. 高亮: syntax/code_highlight.md
                  - 7. 字体样式:
                      - 7.1. 斜体,粗体,粗斜体: syntax/font_stress.md
                      - 7.2. 上标,下标: syntax/font_updown.md
                      - 7.3. 下划线: syntax/font_underline.md
                      - 7.4. 横线: syntax/font_line.md
                      - 7.5. 下划线+横线: syntax/font_underline_line.md
                  - 8. 列表:
                      - 8.1. 无序列表: syntax/list_noseq.md
                      - 8.2. 有序列表: syntax/list_seq.md
                      - 8.3. 任务列表: syntax/list_task.md
                  - 9. 分割线: syntax/cutline.md
                  - 10. 链接:
                      - 10.1. 普通链接: syntax/link_normal.md
                      - 10.2. 自动链接: syntax/link_auto.md
                      - 10.3. 锚点提示: syntax/link_anchor.md
                  - 11. 图片:
                      - 11.1. 行内式: syntax/image_inline.md
                      - 11.2. 参考式: syntax/image_index.md
                  - 12. 转义: syntax/escape.md
                  - 13. 高亮:
                      - 13.1. 代码高亮: syntax/highlight_code.md
                      - 13.2. 背景高亮: syntax/highlight_background.md
                  - 14. 注解:
                      - 14.1. 介绍: syntax/note_main.md
                      - 14.2. 完整格式: syntax/note_full.md
                      - 14.3. 空标题: syntax/note_empty-title.md
                      - 14.4. 无标题: syntax/note_none-title.md
                      - 14.5. 无类型: syntax/note_none-type.md
                      - 14.6. 折叠: syntax/note_details.md
                      - 14.7. 11种颜色样式: syntax/note_style.md
                      - 14.8. 嵌套: syntax/note_nest.md
                  - 15. 脚注: syntax/footnote.md
                  - 16. 元信息: syntax/meta.md
                  - 17. 数学公式:
                      - 17.1. 介绍: syntax/math_main.md
                      - 17.2. 导入js: syntax/math_js.md
                      - 17.3. 用法: syntax/math_usage.md
                  - 18. emoji:
                      - 18.1. 介绍: syntax/emoji_main.md
                      - 18.2. 工作原理: syntax/emoji_principle.md
                      - 18.3. 最佳实践: syntax/emoji_usage.md
                  - 19. 特殊符号: syntax/symbol.md
                  - 20. 嵌套:
                      - 20.1. 介绍: syntax/nest_main.md
                      - 20.2. 注解-注解: syntax/nest_note_note.md
                      - 20.3. 列表-列表: syntax/nest_list_list.md
                      - 20.4. 引用-引用: syntax/nest_quote_quote.md
                      - 20.5. 注解-代码块: syntax/nest_note_code.md
                      - 20.6. 列表-代码块: syntax/nest_list_code.md
                      - 20.7. 引用-代码块: syntax/nest_quote_code.md
                      - 20.8. 黄色区块-代码: syntax/nest_yellow_code.md
                      - 20.9. 绿色区块-代码: syntax/nest_green_code.md
                      - 20.10. 红色区块-代码: syntax/nest_red_code.md
                      - 20.11. 绿接红区块-代码: syntax/nest_greenred_code.md
                      - 20.12. 注解-列表-引用: syntax/nest_note_list_quote.md
                      - 20.13. 列表-列表-引用: syntax/nest_list_list_quote.md
                      - 20.14. 引用-引用-代码: syntax/nest_quote_quote_code.md
              - 四. 附录:
                  - 1. 支持代码高亮的语言: appendix/pygments.md
                  - 2. emojione全名短名映射表: appendix/emoji_shortname.md
                  - 3. 添加百度统计: appendix/baidu_tongji.md
                  - 4. 配色: appendix/color.md
                  - 5. 模块介绍: appendix/module.md
                  - 6. mkdocs层级关系: appendix/level.md
                  - 7. 支持中文搜索: appendix/search.md
                  - 8. mkdocs.yml范例: appendix/yml.md
              - 五. 使用建议: recommend.md
              - 六. 联系方式: contact.md

